### ISSUE TITLE
Connection Pool Size in Sinatra

### ISSUE THREAD

**Issue by jordanthornquest** [chicks/sugarcrm#99]
After I log in with the SugarCRM gem, and when I try to get the first name of the account user's name (`puts SugarCRM::Account.first.name`), I get this error:

``` bash
SugarCRM::ConnectionTimeoutError - could not obtain a sugarcrm connection within 10 seconds. The max pool size is currently 1; consider increasing it.:
```

How can I do this? Is this a Sinatra-specific error, or is it something else?

**Comment by chicks** [comment]
How is the connection being opened?  Does Sinatra magically handle that somehow?

**Comment by jordanthornquest** [comment]
I have code before hand, as well ;)

```
SugarCRM.connect("http://crm.example.com/", "me", "voila")
SugarCRM.connection.debug = true
```

**Comment by jordanthornquest** [comment]
I ran into this same error with IRB as well, interestingly enough.

``` bash
$ irb
$ 2.0.0p247 :001 > require 'sugarcrm'
 => true
$ 2.0.0p247 :002 > SugarCRM.connect("http://crm.example.com", 'me', 'voila')
 => SugarCRM::Namespace0
$ 2.0.0p247 :003 > puts SugarCRM.current_user
SugarCRM::RetryLimitExceeded: SugarCRM::Connection Errors:
SugarCRM::InvalidSession
  SugarCRM::InvalidSession
  SugarCRM::InvalidSession
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:75:in `send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:102:in `rescue in send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:79:in `send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:102:in `rescue in send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:79:in `send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:102:in `rescue in send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/connection.rb:79:in `send!'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/connection/api/get_entry_list.rb:29:in `get_entry_list'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/finders/finder_methods.rb:99:in `find_by_sql'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/finders/finder_methods.rb:6:in `find_initial'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/base.rb:52:in `find'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/finders/finder_methods.rb:182:in `find_by_user_name'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/finders/finder_methods.rb:187:in `method_missing'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/session.rb:166:in `current_user'
    from /Users/jordanthornquest/.rvm/gems/ruby-2.0.0-p247/gems/sugarcrm-0.9.18/lib/sugarcrm/module_methods.rb:63:in `method_missing'
    from (irb):3
    from /Users/jordanthornquest/.rvm/rubies/ruby-2.0.0-p247/bin/irb:13:in `<main>'2.0.0p247 :004 >
```

**Comment by jordanthornquest** [comment]
Update: this was a server issue. We figured it out :)
